# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      # - run: npm run build --if-present
      - run: npm test -- --coverage
        env: # Or as an environment variable
          ROBINHOOD_USERNAME: ${{ secrets.ROBINHOOD_USERNAME }}
          ROBINHOOD_PASSWORD: ${{ secrets.ROBINHOOD_PASSWORD }}
          ROBINHOOD_DEVICE_TOKEN: ${{ secrets.ROBINHOOD_DEVICE_TOKEN }}
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
          ALPACA_PAPER_TRADING: ${{ secrets.ALPACA_PAPER_TRADING }}
          MAILTRAP_EMAIL: ${{ secrets.MAILTRAP_EMAIL }}
          MAILTRAP_USER: ${{ secrets.MAILTRAP_USER }}
          MAILTRAP_PASSWORD: ${{ secrets.MAILTRAP_PASSWORD }}
